common/models/Students.php
<?php

namespace common\models;

use Yii;
use yii\base\ErrorException;
use yii\web\UploadedFile;

/**
 * This is the model class for table "students".
 *
 * @property integer $id
 * @property string $admission_id
 * @property string $roll_number
 * @property string $admission_date
 * @property integer $student_category
 * @property string $first_name
 * @property string $middle_name
 * @property string $last_name
 * @property string $father_name
 * @property string $mother_name
 * @property string $date_of_birth
 * @property string $gender
 * @property string $marital_status
 * @property string $blood_group
 * @property string $birth_place
 * @property integer $nationality_id
 * @property string $language
 * @property string $religion
 * @property string $address_line1
 * @property string $address_line2
 * @property string $city
 * @property string $state
 * @property integer $country_id
 * @property string $phone1
 * @property string $phone2
 * @property string $email
 * @property string $issms_enabled
 * @property string $photo_file_name
 * @property string $photo_file_type
 * @property resource $photo_element_data
 * @property string $description
 * @property string $isactive
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 * @property integer $photo_file_size
 * @property string $signup_request_token
 * @property resource $file
 * @property string $imgpath
 * @property number $jcropX1
 * @property number $jcropY1
 * @property number $jcropW
 * @property number $jcropH
 *
 * @property User $updatedBy
 * @property User $createdBy
 */
class Students extends GeneralRecord
{
    /**
     * @var UploadedFile file attribute
     */
    public $file;

    const STATUS_ACTIVE = 'Active';

    /**
     * @vars photo crop parameters
     */
    public $jcropX1;
    public $jcropY1;
    public $jcropW;
    public $jcropH;

    /**
     * @var default image for users
     */
    public $imgPath;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'students';
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($params)
    {
        if ($this->file = UploadedFile::getInstance($this, 'file')){
            if ($this->validate()) {
                $this->photo_file_name = $this->file->name;
                $this->photo_file_type = $this->file->type;
                $this->photo_file_size = $this->file->size;
                $source = $this->file->tempName;
                $this->implementJcrop($source, $this->file->type);
                $this->photo_element_data = file_get_contents($source);
            }
            else{
                Yii::$app->session->setFlash('danger', 'There was a <b>problem while uploading the photo</b>, please check the file and try again. (Please note: Uploading file should be less than 4MB in size');
                return false;
            }
        }
        $this->isactive = self::STATUS_ACTIVE;

        return parent::beforeSave($params);
    }

    public function beforeDelete()
    {
        $user = User::findOne(Yii::$app->user->identity->getId());
        if ($user->sid != $this->admission_id) {
            if (parent::beforeDelete()) {
                if ($associatedUser = User::findOne(['sid' => $this->admission_id]))
                    $associatedUser->delete();
                return true;
            } else {
                return false;
            }
        }else {
            return false;
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_category', 'nationality_id', 'country_id', 'photo_file_size', 'created_by', 'updated_by'], 'integer'],
            [['photo_element_data', 'description'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['jcropX1', 'jcropY1', 'jcropW', 'jcropH'], 'number'],
            [['admission_id', 'first_name', 'last_name', 'date_of_birth', 'student_category', 'nationality_id', 'address_line1', 'city', 'phone1', 'gender'], 'required'],
            [['file'], 'file', 'extensions' => 'jpg, png', 'mimeTypes' => 'image/jpeg, image/png', 'maxSize' => 4000000],
            [['admission_id', 'roll_number', 'admission_date', 'first_name', 'middle_name', 'last_name', 'father_name', 'mother_name', 'date_of_birth', 'gender', 'marital_status', 'blood_group', 'birth_place', 'language', 'religion', 'address_line1', 'address_line2', 'city', 'state', 'phone1', 'phone2', 'email', 'issms_enabled', 'photo_file_name', 'photo_file_type', 'isactive'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'admission_id' => 'Admission ID',
            'roll_number' => 'Roll Number',
            'admission_date' => 'Admission Date',
            'student_category' => 'Student Category',
            'first_name' => 'First Name',
            'middle_name' => 'Middle Name',
            'last_name' => 'Last Name',
            'father_name' => 'Father Name',
            'mother_name' => 'Mother Name',
            'date_of_birth' => 'Date of Birth',
            'gender' => 'Gender',
            'marital_status' => 'Marital Status',
            'blood_group' => 'Blood Group',
            'birth_place' => 'Birth Place',
            'nationality_id' => 'Nationality ID',
            'language' => 'Language',
            'religion' => 'Religion',
            'address_line1' => 'Address Line 1',
            'address_line2' => 'Address Line 2',
            'city' => 'City',
            'state' => 'State',
            'country_id' => 'Country',
            'phone1' => 'Phone 1',
            'phone2' => 'Phone 2',
            'email' => 'Email',
            'issms_enabled' => 'SMS Subscription',
            'photo_file_name' => 'Photo File Name',
            'photo_file_type' => 'Photo File Type',
            'photo_element_data' => 'Photo Element Data',
            'file' => 'Photo',
            'description' => 'Description',
            'isactive' => 'Status',
            'created_at' => 'Created At',
            'createdBy.username' => 'Created By',
            'updated_at' => 'Updated At',
            'updatedBy.username' => 'Updated By',
        ];
    }

    /**
     * Finds user by signup request token
     *
     * @param string $token signup request token
     * @return null|static
     */
    public static function findBySignupRequestToken($token)
    {
        return static::findOne([
            'signup_request_token' => $token,
            'isactive' => 'Active',
        ]);
    }

    /**
     * Generates new sign up request token
     */
    public function generateSignupRequestToken()
    {
        $this->signup_request_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes signup request token
     */
    public function removeSignupRequestToken()
    {
        $this->signup_request_token = null;
    }

    /**
     * @return array
     * - Returns an array of students in [id => first_name + last_name] pair.
     * Results can be filtered by passing params in Array format.
     * @param array $filter
     * - This can be an array of columns with their desired values
     * to filter while fetching the table for data
     */
    public static function getSpecificStudents($filter = [])
    {
        $students = null;

        $multiArray =  Students::find()
            ->asArray()
            ->select(['id', 'admission_id', 'first_name', 'last_name'])
            ->where($filter)
            ->all();

        foreach($multiArray as $singleArray)
            $students[$singleArray['id']] = $singleArray['admission_id'] .' '. $singleArray['first_name'] .' '. $singleArray['last_name'];

        return $students;
    }

    /**
     * @return integer
     * - Returns the number of records satisfy the given filter.
     * @param array $filter
     * - This can be an array of columns with their desired values
     * to filter while fetching the table for data
     */
    public static function getSpecificCount($filter = [])
    {
        $students = self::getSpecificStudents($filter);
        return count($students);
    }

    /**
     * @return array
     * available gender types
     */
    public function getGenderOptions()
    {
        return ['Male' => 'Male', 'Female' => 'Female'];
    }

    /**
     * @return array
     * available marital options
     */
    public function getMaritalOptions()
    {
        return ['Single' => 'Single', 'Married' => 'Married'];
    }

    /**
     * Jcrop server side implementation. Crops the uploaded image as per Jcrop inputs
     */
    public function implementJcrop($src, $contentType)
    {
        $targetWidth = $targetHeight = 250;
        $jpegQuality = 90;

        if($contentType === 'image/jpeg')
            $image = imagecreatefromjpeg($src);
        elseif($contentType === 'image/png')
            $image = imagecreatefrompng($src);

        $distribution = imagecreatetruecolor($targetWidth, $targetHeight);

        imagecopyresampled($distribution,$image,0,0, $this->jcropX1, $this->jcropY1,
            $targetHeight,$targetHeight, $this->jcropW, $this->jcropH);

        if($contentType === 'image/jpeg')
            imagejpeg($distribution, $src, $jpegQuality);
        elseif($contentType === 'image/png')
            imagepng($distribution, $src);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
}

frontend/controllers/EmployeesController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Employees;
use common\models\EmployeesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EmployeesController implements the CRUD actions for Employees model.
 */
class EmployeesController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Employees models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EmployeesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Employees model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Employees model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Employees();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Employees model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Employees model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if ($this->findModel($id)->delete())
            return $this->redirect(['index']);
        else{
            Yii::$app->getSession()->setFlash('danger', 'Sorry, we are unable to process your request. Please make sure that the currently logged in User ID is not associated with the employee record you want to delete.');
            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the Employees model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Employees the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Employees::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionLoadImage($id)
    {
        $model = $this->findModel($id);

        //header("content-type: " + $model->photo_file_type);
        echo $model->photo_element_data;

    }
}

frontend/views/employees/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* Date Picker asset has been added to support Date picking feature */
$this->registerAssetBundle('app\assets\DatePickerAsset');
/* Form Wizard asset has been added to support Form Wizard feature */
$this->registerAssetBundle('app\assets\FormWizardAsset');

/* @var $this yii\web\View */
/* @var $model common\models\Employees */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="panel panel-default">
    <div class="panel-body no-p">
        <div id="wizard" class="wizard">
            <ul class="steps">
                <li data-target="#step1" class="active">
                    <span class="badge bg-info">1</span>Basic Details
                </li>
                <li data-target="#step2">
                    <span class="badge bg-info">2</span>Personal Details
                </li>
                <li data-target="#step3">
                    <span class="badge bg-info">3</span>Contact Details
                </li>
                <li data-target="#step4">
                    <span class="badge bg-info">4</span>Miscellaneous
                </li>
            </ul>
            <div class="btn-group sc-wizard-btns">
                <button class="btn btn-default btn-sm btn-prev mr20">
                    <i class="fa fa-angle-left"></i>&nbsp; Go Back
                </button>
                <button class="btn btn-primary btn-sm btn-next">
                    Continue with <?= $task ?> &nbsp;<i class="fa fa-angle-right"></i>
                </button>
            </div>
        </div>
            <div class="step-content">
            <?php $form = ActiveForm::begin([
                'options' => [
                    'enctype' => 'multipart/form-data',
                ],
                'fieldConfig' => [
                    'options' => [
                        'class' => 'form-group col-md-6',
                    ],
                    'template' => '{label}<div>{input}</div>',
                ],
            ]); ?>
                <div class="step-pane active" id="step1">
                    <div class="row">
                        <div class="col-md-12">
                            <?= $form->field($model, 'employee_id')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'first_name')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'middle_name')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'last_name')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'job_title')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'employee_category')->textInput() ?>

                            <?= $form->field($model, 'employee_position_id')->textInput() ?>

                            <?= $form->field($model, 'employee_department_id')->textInput() ?>

                            <?= $form->field($model, 'reporting_manager_id')->textInput() ?>

                            <?= $form->field($model, 'employee_grade_id')->textInput() ?>

                            <?= $form->field($model, 'qualification')->textInput() ?>

                            <?= $form->field($model, 'joining_date',  [
                                'inputOptions' => [
                                    'class' => 'form-control datepicker',
                                ],
                            ])->textInput() ?>

                            <?= $form->field($model, 'experience_years')->textInput() ?>

                            <?= $form->field($model, 'experience_months')->textInput() ?>

                            <?= $form->field($model, 'experience_details')->textarea(['rows' => 6]) ?>

                        </div>
                    </div>
                </div>
                <div class="step-pane" id="step2">
                    <div class="row">
                        <div class="col-md-12">
                            <?= $form->field($model, 'father_name')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'mother_name')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'spouse_name')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'date_of_birth',  [
                                'inputOptions' => [
                                    'class' => 'form-control datepicker',
                                ],
                            ])->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'gender')->dropDownList($model->genderOptions,[
                                'prompt' => 'Choose One',
                            ]) ?>

                            <?= $form->field($model, 'marital_status')->dropDownList($model->maritalOptions,[
                                'prompt' => 'Choose One',
                            ]) ?>

                            <?= $form->field($model, 'children_count')->textInput() ?>

                            <?= $form->field($model, 'blood_group')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'birth_place')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'nationality_id')->textInput() ?>

                            <?= $form->field($model, 'language')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'religion')->textInput(['maxlength' => 255]) ?>

                        </div>
                    </div>
                </div>
                <div class="step-pane" id="step3">
                    <div class="row">
                        <div class="col-md-12">
                            <?= $form->field($model, 'present_address_line1')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'present_address_line2')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'present_city')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'present_state')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'present_country_id')->textInput() ?>

                            <?= $form->field($model, 'present_phone1')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'present_phone2')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'present_mobile')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'fax')->textInput(['maxlength' => 255]) ?>

                            <div class="col-md-12 no-p"><?= $form->field($model, 'copyPresentAddress')->checkbox() ?></div>

                            <?= $form->field($model, 'permanent_address_line1')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'permanent_address_line2')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'permanent_city')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'permanent_state')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'permanent_country_id')->textInput() ?>

                            <?= $form->field($model, 'permanent_phone1')->textInput(['maxlength' => 255]) ?>

                            <?= $form->field($model, 'permanent_phone2')->textInput(['maxlength' => 255]) ?>
                        </div>
                    </div>
                </div>
                <div class="step-pane" id="step4">
                    <div class="row">
                        <div class="col-md-12">

                            <?= $form->field($model, 'file')->fileInput() ?>

                            <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/employees/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Employees */

$this->title = 'Create Employees';
$this->params['breadcrumbs'][] = ['label' => 'User Management', 'url' => ['user-management/index']];
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employees-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'task' => 'induction',
    ]) ?>

</div>

frontend/views/employees/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Employees */

$this->title = 'Update Employee: ' . ' ' . $model->first_name;
$this->params['breadcrumbs'][] = ['label' => 'User Management', 'url' => ['user-management/index']];
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->first_name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="employees-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'task' => 'modifications',
    ]) ?>

</div>

frontend/views/employees/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Employees */

$this->title = $model->first_name;
$this->params['breadcrumbs'][] = ['label' => 'User Management', 'url' => ['user-management/index']];
$this->params['breadcrumbs'][] = ['label' => 'Employees', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-lg-12">
        <section class="panel no-b">
            <div class="panel-body p25">
                <div class="col-md-3">
                    <?php if($model->photo_file_name) {
                        $model->imgPath = Yii::$app->urlManager->createAbsoluteUrl(['employees/load-image', 'id' => $model->id]);
                    }
                    else{
                        if($model->gender == 'Female')
                            $model->imgPath = 'http://s3.postimg.org/ptksq2olb/default_female.jpg';
                        else
                            $model->imgPath = 'http://s16.postimg.org/z26pdgnzl/default_male.jpg';
                    }
                    ?>
                    <a href="javascript:;" class="show text-center">
                        <img src="<?= $model->imgPath  ?>" class="avatar avatar-lg img-circle" alt="">
                    </a>

                    <div class="show mt15 text-center">
                        <div class="h5"><b><?= $model->first_name .' '. $model->middle_name .' '. $model->last_name ?></b>
                        </div>
                        <p class="mb25">Adm ID: <b><?= $model->employee_id ?></b></p>
                    </div>
                </div>
                <div class="col-md-6 table-responsive text-center">
                    <table class="table">
                        <tr>
                            <td class="no-b">Batch:</td><td class="no-b">Grade 7 A 2014</td>
                        </tr>
                        <tr>
                            <td>Age:</td><td>24 (DOB: <?= $model->date_of_birth ?> )</td>
                        </tr>
                        <tr>
                            <td>Category:</td><td>SC / ST</td>
                        </tr>
                        <tr>
                            <td>Transport:</td><td>Not subscribed</td>
                        </tr>
                        <tr>
                            <td>Hostel:</td><td>Not subscribed</td>
                        </tr>
                    </table>
                    <label class="bg-default p5 b-radius5 ml10 mb10 pull-left"><i class="fa fa-check"></i> Enrolled on <b>Scintin</b></label>
                    <label class="bg-default p5 b-radius5 ml10 mb10 pull-left"><i class="fa fa-check"></i> No Fee <b>Dues</b></label>
                </div>
                <div class="col-md-3 pull-right">
                    <p>
                        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                            'class' => 'btn btn-danger pull-right',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]) ?>
                        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary pull-right mr10']) ?>
                    </p>
                </div>

            </div>
            <div class="col-md-12 bg-white">
                <h2 class="mt5">More details</h2>
                <div class="table-responsive">
                    <?= DetailView::widget([
                        'model' => $model,
                        'options' => [
                            'class' => 'table col-md-6 view-table'
                        ],
                        'attributes' => [
                            // 'id',
                            'employee_id',
                            'joining_date',
                            'employee_category',
                            'first_name',
                            'middle_name',
                            'last_name',
                            'job_title',
                            'employee_position_id',
                            'employee_department_id',
                            'reporting_manager_id',
                            'employee_grade_id',
                            'qualification',
                            'experience_details:ntext',
                            'experience_years',
                            'experience_months',
                            'father_name',
                            'mother_name',
                            'spouse_name',
                            'date_of_birth',
                            'gender',
                            'marital_status',
                            'children_count',
                            'blood_group',
                            'birth_place',
                            'nationality_id',
                            'language',
                            'religion',
                            'present_address_line1',
                            'present_address_line2',
                            'present_city',
                            'present_state',
                            'present_country_id',
                            'present_phone1',
                            'present_phone2',
                            'present_mobile',
                            'email:email',
                            'fax',
                            'permanent_address_line1',
                            'permanent_address_line2',
                            'permanent_city',
                            'permanent_state',
                            'permanent_country_id',
                            'permanent_phone1',
                            'permanent_phone2',
                            'description:ntext',
                            'isactive',
                            'created_at',
                            'createdBy.username',
                            'updated_at',
                            'updatedBy.username',
                        ],
                    ]) ?>
                </div>
            </div>
        </section>
    </div>
</div>