common/models/Subjects.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "subjects".
 *
 * @property integer $id
 * @property string $subject_name
 * @property string $subject_code
 * @property string $subject_type
 * @property string $iselective
 * @property integer $elective_group
 * @property string $parent_type
 * @property integer $course_id
 * @property integer $batch_id
 * @property integer $weekly_classes_max
 * @property integer $language
 * @property integer $credit_hours
 * @property integer $dependant_on
 * @property string $isactive
 * @property string $noexam
 * @property string $created_at
 * @property integer $created_by
 * @property string $updated_at
 * @property integer $updated_by
 *
 * @property Batches $batch
 * @property Courses $course
 * @property Subjects $dependantOn
 * @property Subjects[] $subjects
 * @property ElectiveGroups $electiveGroup
 * @property User $createdBy
 * @property User $updatedBy
 */
class Subjects extends GeneralRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'subjects';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['elective_group', 'course_id', 'batch_id', 'weekly_classes_max', 'language', 'credit_hours', 'dependant_on', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['subject_name', 'subject_code', 'subject_type', 'iselective', 'parent_type', 'isactive', 'noexam'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'subject_name' => 'Subject Name',
            'subject_code' => 'Subject Code',
            'subject_type' => 'Subject Type',
            'iselective' => 'Subject Group',
            'elective_group' => 'Elective Group',
            'parent_type' => 'Parent Type',
            'course_id' => 'Course ID',
            'batch_id' => 'Batch ID',
            'weekly_classes_max' => 'Weekly Classes Max',
            'language' => 'Language',
            'credit_hours' => 'Credit Hours',
            'dependant_on' => 'Dependant On',
            'isactive' => 'Status',
            'noexam' => 'Exam Based',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        $return = parent::beforeSave($insert);

        switch($this->parent_type)
        {
            case 'Course':
                $this->batch_id = null;
                break;
            case 'Batch':
                $this->course_id = null;
                break;
        }

        if($this->iselective === 'Mandatory')
            $this->elective_group = null;

        if($this->dependant_on === 'No options available')
            $this->dependant_on = null;

        return $return;
    }

    /**
     * @return array
     * - Subject type options
     */
    public function getSubjectTypes()
    {
        return ['Theory' => 'Theory', 'Practicals' => 'Practicals'];
    }

    /**
     * @return array
     * - Subject group options
     */
    public function getSubjectGroups()
    {
        return ['Mandatory' => 'Mandatory', 'Elective' => 'Elective'];
    }

    /**
     * @return array
     * - Subject parent options
     */
    public function getParentOptions()
    {
        return ['Course' => 'Course', 'Batch' => 'Batch'];
    }

    /**
     * @return array
     * - Subject status options
     */
    public function getSubjectStatus()
    {
        return ['Active' => 'Active', 'Inactive' => 'Inactive'];
    }

    /**
     * @return array
     * - Exam options
     */
    public function getExamOptions()
    {
        return ['Yes' => 'Yes', 'No' => 'No'];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBatch()
    {
        return $this->hasOne(Batches::className(), ['id' => 'batch_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCourse()
    {
        return $this->hasOne(Courses::className(), ['id' => 'course_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDependantOn()
    {
        return $this->hasOne(Subjects::className(), ['id' => 'dependant_on']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubjects()
    {
        return $this->hasMany(Subjects::className(), ['dependant_on' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getElectiveGroup()
    {
        return $this->hasOne(ElectiveGroups::className(), ['id' => 'elective_group']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return array
     * - Returns an array of subjects in [id => subject_name] pair.
     * Results can be filtered by passing params in Array format.
     * @param array $filter
     * - This can be an array of columns with their desired values
     * to filter while fetching the table for data
     */
    public static function getSpecificSubjects($filter = [])
    {
        $subjects = null;

        $multiArray =  Subjects::find()
            ->asArray()
            ->select(['id','subject_name'])
            ->where($filter)
            ->all();

        foreach($multiArray as $singleArray)
            $subjects[$singleArray['id']] = $singleArray['subject_name'];

        return $subjects;
    }

    /**
     * @return integer
     * - Returns the number of records satisfy the given filter.
     * @param array $filter
     * - This can be an array of columns with their desired values
     * to filter while fetching the table for data
     */
    public static function getSpecificCount($filter = [])
    {
        $subjects = self::getSpecificSubjects($filter);
        return count($subjects);
    }
}

frontend/controllers/SubjectsController.php
<?php

namespace frontend\controllers;

use common\models\Batches;
use common\models\Courses;
use common\models\ElectiveGroups;
use Yii;
use common\models\Subjects;
use common\models\SubjectsSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;

/**
 * SubjectsController implements the CRUD actions for Subjects model.
 */
class SubjectsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => ['create-subject'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['view-subject'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Subjects models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SubjectsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Subjects model.
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if(Yii::$app->user->can('view-subject', ['model' => $model])) {
            return $this->render('view', [
                'model' => $model,
            ]);
        }
        else
        {
            throw new ForbiddenHttpException('You are not authorized to perform this action.');
        }
    }

    /**
     * Creates a new Subjects model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Subjects();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            //filters - { Must be active }
            $filter = [
                'isactive' => 'Active'
            ];

            if(!($activeElectiveGroups = ElectiveGroups::getSpecificElectiveGroups($filter)))
                $activeElectiveGroups = ['Not available' => 'No options available'];
            if(!($activeCourses = Courses::getSpecificCourses($filter)))
                $activeCourses = ['Not available' => 'No options available'];
            if(!($activeBatches = Batches::getSpecificBatches([],$filter)))
                $activeBatches = ['Not available' => 'No options available'];
            if(!($activeSubjects = Subjects::getSpecificSubjects($filter)))
                $activeSubjects = [];

            if($activeCourses === ['Not available' => 'No options available']) {
                Yii::$app->session->setFlash('danger', 'There must be atleast one <b>active course</b> registered in the database before creating a Subject');
                return Yii::$app->response->redirect(['courses/overview']);
            }
            else
                return $this->render('create', [
                    'model' => $model,
                    'activeElectiveGroups' => $activeElectiveGroups,
                    'activeCourses' => $activeCourses,
                    'activeBatches' => $activeBatches,
                    'activeSubjects' => $activeSubjects,
                ]);
        }
    }

    /**
     * Updates an existing Subjects model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if(Yii::$app->user->can('update-subject', ['model' => $model]))
        {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                //filters - { Must be active }
                $filter = [
                    'isactive' => 'Active'
                ];

                if(!($activeElectiveGroups = ElectiveGroups::getSpecificElectiveGroups($filter)))
                    $activeElectiveGroups = ['Not available' => 'No options available'];
                if(!($activeCourses = Courses::getSpecificCourses($filter)))
                    $activeCourses = ['Not available' => 'No options available'];
                else
                    $parentOptions['Course'] = 'Course';
                if(!($activeBatches = Batches::getSpecificBatches([],$filter)))
                    $activeBatches = ['Not available' => 'No options available'];
                else
                    $parentOptions['Batch'] = 'Batch';
                if(!($activeSubjects = Subjects::getSpecificSubjects($filter)))
                    $activeSubjects = [];
                if(!isset($parentOptions)) {
                    Yii::$app->session->setFlash('danger', 'There must be atleast one <b>active course</b> registered in the database before creating a Subject');
                    return Yii::$app->response->redirect(['courses/overview']);
                }
                else
                    return $this->render('update', [
                        'model' => $model,
                        'activeElectiveGroups' => $activeElectiveGroups,
                        'parentOptions' => $parentOptions,
                        'activeCourses' => $activeCourses,
                        'activeBatches' => $activeBatches,
                        'activeSubjects' => $activeSubjects,
                    ]);
            }
        }else
        {
            throw new ForbiddenHttpException('You are not authorized to perform this action.');
        }
    }

    /**
     * Deletes an existing Subjects model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if(Yii::$app->user->can('delete-subject', ['model' => $model])) {
            $model->delete();
            return $this->redirect(['index']);
        }else {
            throw new ForbiddenHttpException('You are not authorized to perform this action.');
        }
    }

    /**
     * Finds the Subjects model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Subjects the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Subjects::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/subjects/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->registerJs('
    function hideElectives(){
        if($("#subjects-iselective").val() == "Elective"){
            if($("#subjects-elective_group").val() == "Not available"){
                alert("Please create an Elective Group prior to creation of Elective Subjects");
                $("#subjects-iselective").val("Mandatory");
            }
            else{
                $(".field-subjects-elective_group").slideDown();
            }
        }
        else{
            $(".field-subjects-elective_group").slideUp();
        }
    }

    function hideCourseBatch(){
            if($("#subjects-parent_type").val() == "Course"){
                $(".field-subjects-course_id").slideDown();
                $(".field-subjects-batch_id").slideUp();
            }
            else if($("#subjects-parent_type").val() == "Batch" && $("#subjects-batch_id").val() != "Not available"){
                    $(".field-subjects-batch_id").slideDown();
                    $(".field-subjects-course_id").slideUp();
            }
            else{
                alert("There are no active batches available in the database");
                $("#subjects-parent_type").val("Course");
            }
    }

    hideCourseBatch();
    hideElectives();

    $("#subjects-iselective").change(function(){
        hideElectives();
    });

    $("#subjects-parent_type").change(function(){
        hideCourseBatch();
    });
');

/* @var $this yii\web\View */
/* @var $model common\models\Subjects */
/* @var $form yii\widgets\ActiveForm */
?>

    <?php $form = ActiveForm::begin([
        'layout' => 'horizontal',
        'fieldConfig' => [
            'labelOptions' => [
                'class' => 'col-md-2 control-label',
            ],
            'template' => '{label}<div class="col-md-8">{input}</div>{error}'
        ],
    ]); ?>

    <?= $form->field($model, 'subject_name')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'subject_code')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'subject_type')->dropDownList($model->subjectTypes) ?>

    <?= $form->field($model, 'iselective')->dropDownList($model->subjectGroups) ?>

    <?= $form->field($model, 'elective_group')->dropDownList($activeElectiveGroups) ?>

    <?= $form->field($model, 'parent_type')->dropDownList($model->parentOptions) ?>

    <?= $form->field($model, 'course_id')->dropDownList($activeCourses) ?>

    <?= $form->field($model, 'batch_id')->dropDownList($activeBatches) ?>

    <?= $form->field($model, 'weekly_classes_max')->textInput() ?>

    <?= $form->field($model, 'language')->textInput() ?>

    <?= $form->field($model, 'credit_hours')->textInput() ?>

    <?= $form->field($model, 'dependant_on')->dropDownList($activeSubjects,[
        'prompt' => '--- None ---'
    ]) ?>

    <?= $form->field($model, 'isactive')->dropDownList($model->subjectStatus) ?>

    <?= $form->field($model, 'noexam')->dropDownList($model->examOptions) ?>


    <div class="form-group">
        <div class="col-md-2 control-label"></div>
        <div class="col-md-8">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', [
                'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary',
                'type' => 'submit',
            ]) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

frontend/views/subjects/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\SubjectsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="subjects-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'subject_name') ?>

    <?= $form->field($model, 'subject_code') ?>

    <?= $form->field($model, 'subject_type') ?>

    <?= $form->field($model, 'iselective') ?>

    <?php // echo $form->field($model, 'elective_group') ?>

    <?php // echo $form->field($model, 'parent_type') ?>

    <?php // echo $form->field($model, 'course_id') ?>

    <?php // echo $form->field($model, 'batch_id') ?>

    <?php // echo $form->field($model, 'weekly_classes_max') ?>

    <?php // echo $form->field($model, 'language') ?>

    <?php // echo $form->field($model, 'credit_hours') ?>

    <?php // echo $form->field($model, 'dependant_on') ?>

    <?php // echo $form->field($model, 'isactive') ?>

    <?php // echo $form->field($model, 'noexam') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/subjects/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Subjects */

$this->title = 'Create Subjects';
$this->params['breadcrumbs'][] = ['label' => 'Courses + Batches', 'url' => ['courses/overview']];
$this->params['breadcrumbs'][] = ['label' => 'Subjects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<section class="panel">
    <header class="panel-heading">
        <h2 class="no-m"><?= Html::encode($this->title) ?></h2>
    </header>
    <div class="panel-body">

        <?= $this->render('_form', [
            'model' => $model,
            'activeElectiveGroups' => $activeElectiveGroups,
            'activeCourses' => $activeCourses,
            'activeBatches' => $activeBatches,
            'activeSubjects' => $activeSubjects,
        ]) ?>

    </div>
</section>

frontend/views/subjects/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\SubjectsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//restricting controls as per user role
$webUser = Yii::$app->user;

$this->title = 'Subjects';
$this->params['breadcrumbs'][] = ['label' => 'Courses + Batches', 'url' => ['courses/overview']];
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- New version -->
<section class="panel panel-default">
    <div class="panel-heading">
        <h1 class="no-m"><?= Html::encode($this->title) ?></h1>
        <?php //echo $this->render('_search', ['model' => $searchModel]); ?>
    </div>
    <div class="panel-body">
        <p>
            <?php
            if($webUser->can('create-subject'))
                echo Html::a('Create Subject', ['create'], ['class' => 'btn btn-success'])
            ?>
        </p>
        <div class="table-responsive">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'class' => 'yii\grid\SerialColumn',
                        'header' => 'S.No'
                    ],
                    'subject_name',
                    'subject_code',
                    'subject_type',
                    'iselective',
                    // 'elective_group',
                    // 'parent_type',
                    // 'course_id',
                    // 'batch_id',
                    // 'weekly_classes_max',
                    // 'language',
                    // 'credit_hours',
                    // 'dependant_on',
                    'isactive',
                    'noexam',
                    // 'created_at',
                    // 'created_by',
                    // 'updated_at',
                    // 'updated_by',

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'contentOptions' => [
                            'class' => 'text-center',
                        ],
                    ],
                ],
            ]); ?>
        </div>
    </div>
</section>

frontend/views/subjects/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Subjects */

$this->title = 'Update Subjects: ' . ' ' . $model->subject_name;
$this->params['breadcrumbs'][] = ['label' => 'Courses + Batches', 'url' => ['courses/overview']];
$this->params['breadcrumbs'][] = ['label' => 'Subjects', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->subject_name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>

<section class="panel">
    <header class="panel-heading">
        <h2 class="no-m"><?= Html::encode($this->title) ?></h2>
    </header>
    <div class="panel-body">

        <?= $this->render('_form', [
            'model' => $model,
            'activeElectiveGroups' => $activeElectiveGroups,
            'activeCourses' => $activeCourses,
            'activeBatches' => $activeBatches,
            'activeSubjects' => $activeSubjects,
        ]) ?>

    </div>
</section>

frontend/views/subjects/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Subjects */

//restricting controls as per user role
$webUser = Yii::$app->user;

$this->title = $model->subject_name;
$this->params['breadcrumbs'][] = ['label' => 'Courses + Batches', 'url' => ['courses/overview']];
$this->params['breadcrumbs'][] = ['label' => 'Subjects', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="panel panel-default">
    <div class="panel-heading">
        <h1 class="no-m"><?= Html::encode($this->title) ?></h1>
    </div>
    <div class="panel-body">
        <p>
            <?php
            if($webUser->can('update-subject', ['model' => $model]))
                echo Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary'])
            ?>
            <?php
            if($webUser->can('delete-subject', ['model' => $model]))
                echo Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ])
            ?>
        </p>

        <?= DetailView::widget([
            'model' => $model,
            'template' => "<tr><th class='col-xs-5 col-md-3'>{label}</th><td>{value}</td></tr>",
            'attributes' => [
                'subject_name',
                'subject_code',
                'subject_type',
                'iselective',
                'elective_group',
                'parent_type',
                'course_id',
                'batch_id',
                'weekly_classes_max',
                'language',
                'credit_hours',
                'dependant_on',
                'isactive',
                'noexam',
                'created_at',
                'createdBy.username',
                'updated_at',
                'updatedBy.username',
            ],
        ]) ?>
    </div>
</section>