backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\rbac\AuthorRule;
use frontend\models\SignupRequestForm;
use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['signup','login', 'request-password-reset', 'reset-password', 'signup-request'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        $this->layout = 'login';

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success');
            } else {
                Yii::$app->session->setFlash('error');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionDashboard()
    {
        return $this->render('dashboard');
    }


    public function actionSignupRequest()
    {
        $this->layout = 'login';

        $model = new SignupRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to process your signup request.');
            }
        }

        return $this->render('signupRequest', [
            'model' => $model,
        ]);

    }

    public function actionSignup($token, $type)
    {
        $this->layout = 'login';

        try {
            $model = new SignupForm($token, $type);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $this->layout = 'login';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        $this->layout = 'login';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Temporary Method to implement AdHoc RBAC
     */
    public function actionRbac()
    {
        Yii::$app->authManager->removeAll();
    }

    /**
     * Temporary Method to implement AdHoc RBAC
     */
    public function actionMiniRbac()
    {
        $rbac = Yii::$app->authManager;


        //Course Permissions
        if(!($createCourse = $rbac->getPermission('create-course')))
        {
            $createCourse = $rbac->createPermission('create-course');
            $createCourse->description = 'Access to create courses';
            $rbac->add($createCourse);
        }

        if(!($viewCourse = $rbac->getPermission('view-course')))
        {
            $viewCourse = $rbac->createPermission('view-course');
            $viewCourse->description = 'Access to view courses';
            $rbac->add($viewCourse);
        }

        if(!($viewOwnCourse = $rbac->getPermission('view-own-course')))
        {
            $viewOwnCourse = $rbac->createPermission('view-own-course');
            $viewOwnCourse->description = 'Access to view own courses';
            $rbac->add($viewOwnCourse);
        }

        if(!($updateCourse = $rbac->getPermission('update-course')))
        {
            $updateCourse = $rbac->createPermission('update-course');
            $updateCourse->description = 'Access to update courses';
            $rbac->add($updateCourse);
        }

        if(!($updateOwnCourse = $rbac->getPermission('update-own-course')))
        {
            $updateOwnCourse = $rbac->createPermission('update-own-course');
            $updateOwnCourse->description = 'Access to update own courses';
            $rbac->add($updateOwnCourse);
        }

        if(!($deleteCourse = $rbac->getPermission('delete-course')))
        {
            $deleteCourse = $rbac->createPermission('delete-course');
            $deleteCourse->description = 'Access to delete own courses';
            $rbac->add($deleteCourse);
        }

        if(!($deleteOwnCourse = $rbac->getPermission('delete-own-course')))
        {
            $deleteOwnCourse = $rbac->createPermission('delete-own-course');
            $deleteOwnCourse->description = 'Access to delete own courses';
            $rbac->add($deleteOwnCourse);
        }


        //Batch Permissions
        if(!($createBatch = $rbac->getPermission('create-batch')))
        {
            $createBatch = $rbac->createPermission('create-batch');
            $createBatch->description = 'Access to create batches';
            $rbac->add($createBatch);
        }

        if(!($viewBatch = $rbac->getPermission('view-batch')))
        {
            $viewBatch = $rbac->createPermission('view-batch');
            $viewBatch->description = 'Access to view batches';
            $rbac->add($viewBatch);
        }

        if(!($viewOwnBatch = $rbac->getPermission('view-own-batch')))
        {
            $viewOwnBatch = $rbac->createPermission('view-own-batch');
            $viewOwnBatch->description = 'Access to view own batches';
            $rbac->add($viewOwnBatch);
        }

        if(!($updateBatch = $rbac->getPermission('update-batch')))
        {
            $updateBatch = $rbac->createPermission('update-batch');
            $updateBatch->description = 'Access to update batches';
            $rbac->add($updateBatch);
        }

        if(!($updateOwnBatch = $rbac->getPermission('update-own-batch')))
        {
            $updateOwnBatch = $rbac->createPermission('update-own-batch');
            $updateOwnBatch->description = 'Access to update own batches';
            $rbac->add($updateOwnBatch);
        }

        if(!($deleteBatch = $rbac->getPermission('delete-batch')))
        {
            $deleteBatch = $rbac->createPermission('delete-batch');
            $deleteBatch->description = 'Access to delete own batches';
            $rbac->add($deleteBatch);
        }

        if(!($deleteOwnBatch = $rbac->getPermission('delete-own-batch')))
        {
            $deleteOwnBatch = $rbac->createPermission('delete-own-batch');
            $deleteOwnBatch->description = 'Access to delete own batches';
            $rbac->add($deleteOwnBatch);
        }

        //Subject Permissions
        if(!($createSubject = $rbac->getPermission('create-subject')))
        {
            $createSubject = $rbac->createPermission('create-subject');
            $createSubject->description = 'Access to create subjects';
            $rbac->add($createSubject);

frontend/views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model frontend\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">

<!-- B - New Division -->
<div class="row">
    <div class="col-lg-8">
        <?php if (Yii::$app->session->hasFlash('success')): ?>

            <div class="alert alert-success">
                Thank you for contacting us. We will respond to you as soon as possible.
            </div>

        <?php elseif (Yii::$app->session->hasFlash('error')): ?>

            <div class="alert alert-warning">
                There was an internal problem while processing your request. Please try again later.
            </div>

        <?php else: ?>
        <section class="panel">
            <header class="panel-heading">
                <h1 class="scintin-h1"><?= Html::encode($this->title) ?></h1>
                If you have business inquiries or other questions, please fill out the following form to contact us.
            </header>
            <div class="panel-body">
                <?php $form = ActiveForm::begin([
                    'id' => 'contact-form',
                ]); ?>

                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-2">{image}</div><div class="col-lg-5">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', [
                        'class' => 'btn btn-primary',
                        'name' => 'login-button',
                        'type' => 'submit',
                    ]) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </section>
        <?php endif; ?>
    </div>
</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model frontend\models\ContactForm */

$this->title = 'Introduction';
?>
<div class="site-index">

    <div class="jumbotron text-center mb0">
        <h1>SCINTIN</h1>
        <p class="lead">AN ERP + SCHOOL NETWORK PROJECT</p>
        <p><a class="btn btn-lg btn-primary" href="<?= Yii::$app->urlManager->createUrl('site/dashboard') ?>">Dashboard (sample)</a></p>
    </div>

    <div class="body-content pl25 pr25 pb20 bg-white">
        <div class="row">
            <div class="col-lg-8">

                    <h2 id="introduction">Introduction</h2>
                    <p>
                        SCINTIN is an ERP + School Network project. The aim of this project is to create a 4th generation Enterprise resource planner which can address all the issues involved in administering a school/college. Being a next generation ERP, it doesn’t stop with financial and administrative functions but also extends up to school network and integrates all the academic, administrative and social functions into one big application and we tentatively named it SCINTIN. Considering the scope and functionality of this application, SCINTIN can be recognized as an abbreviation for “<b>S</b>​c​hool <b>C</b>​o​llege <b>I</b>​n​stitutional <b>N​</b>e<b>​T</b>​w​ork <b>I​N</b>t​egrator”.
                    </p>
                    <br>

                    <h2 id="inspiration">Inspiration</h2>
                    <p>
                        SCINTIN is an inspiration from Fedena, a popular all-in-one software for school and colleges. Though it has a solid ERP structure to hold administrative and finance data of an institution, it lacks flexibility and customization. It provides a very basic school network functionality and poor GUI due to which users (Students, teachers and parents) may not be able to use it as a part of their everyday business.
                    </p>
                    <p>
                        Considering many such aspects, we have decided to build a solid ERP which is customizable as per the school needs and a feature rich school network which enables students, employees and parents to connect to the school effortlessly. Being a comprehensive School/College software, it handles various aspects of school administration. below is the list of identified core categories which feature in SCINTIN.
                    </p>
                    <ul>
                        <li>Finances (fee, payslips, definition of cost centres etc.)</li>
                        <li>Academics (courses, batches, exams, results, research, assignments etc.)</li>
                        <li>Library (books, transactions, fines, library fee, etc.)</li>
                        <li>School (school data, stats, achievements, hall of fame etc.)</li>
                        <li>Social (news, people, chatting, group discussions, media sharing etc.)</li>
                        <li>Sports (teams, coaches, squads, resources, fitness schedules etc.)</li>
                        <li>Hostel (types of rooms, subscriptions, remarks, food etc.)</li>
                        <li>Transport (routes, bus stops, drivers, vehicles etc.)</li>
                    </ul>
                    <br>
                    <img src="img/ScintinBD.jpg" width="600">
                    <br><br>

                    <h2 id="technical_details">Technical Details</h2>
                    <p>
                        This project is being developed right from scratch. PHP and Javascript are the two major languages which are being used while developing this application. This application is based on bootstrap and Yii Framework 2.0. Yii Framework is one of the best framework which supports
                        ORM (Object Relational Mapping), AJAX-enabled widgets, Web services, Internationalization (Multilingual software) and many more such 4th generation concepts. SCINTIN follows a traditional MVC architecture which makes it easy for customization and scalability.
                    </p>
                    <p>
                        So many cutting-edge APIs and plug-ins are being integrated to make sure that this application is highly advanced and provides the best GUI experience by the time it is released. Few APIs such as Google Maps (transport), Google Calendars (events, exams and assignments) and Google Drive (file/media sharing) can take this application to next level.
                    </p>
                    <p>
                        This application supports both Oracle and MySQL as its database which gives more options for the school which implements SCINTIN. Ideally, SCINTIN has to be hosted on AWS - Amazon Web services.
                    </p>
                    <br>
                    <img src="img/ScintinTL.jpg" width="600">
                    <br><br>

                    <h2 id="security_concepts">Security Concepts</h2>

                    <p>
                        Since this entire application is being hosted on cloud and can be accessed through web browsers and APIs, security is being considered as the most important aspect of the entire project. Our security architecture is based on Yii 2.0 framework and RBAC concepts. Security measures include c​ross-site scripting ​(XSS) prevention, c​ross-site request forgery​ (CSRF) prevention, c​ookie​tampering prevention, etc. SCINTIN users are ideally mapped to their google accounts in order to enjoy access to all features (few features are powered by Google Apps).
                    </p>
                    <br><br>

                    <p id="credentials"><b>A joint effort of</b><br>
                        Manideep Bollu - m​anideep@msn.com​ <br>
                        Kalyan Venkat - k​alyan.venkat21@gmail.com <br>
                        Reddy Girish Gaddam - gaddamreddygirish@gmail.com
                    ​</p>
            </div>
            <div class="col-lg-4">
                <!-- Bollu -> Know more section begins -->
                <section class="panel mt15">
                    <div class="panel-heading">
                        <b>What are we up to?</b>
                    </div>
                    <div class="panel-body">
                        <ul class="pl20">
                            <li>
                                <a href="#introduction">
                                    <span>Introduction</span>
                                </a>
                            </li>
                            <li>
                                <a href="#inspiration">
                                    <span>Inspiration</span>
                                </a>
                            </li>
                            <li>
                                <a href="#technical_details">
                                    <span>Technical Details</span>
                                </a>
                            </li>
                            <li>
                                <a href="#security_concepts">
                                    <span>Security Concepts</span>
                                </a>
                            </li>
                            <li>
                                <a href="#credentials">
                                    <span>Credentials</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </section>
                <!-- Bollu -> Know more section ends -->
            </div>
        </div>
    </div>
</div>

frontend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model common\models\LoginForm */

$this->title = 'Login';

/* @var $this->params['login', 'signup'] - Manually introduced variables to toggle "Active class" between
 * login and Signup pages at layout.*/
$this->params = [
    'login' => 'active',
    'signup' => '',
];
?>
<!-- B - New Division -->

<?php $form = ActiveForm::begin([
    'id' => 'login-form',
    'layout' => 'default',
    'fieldConfig' => [
        'template' => '{input}<div class="help-block help-block-error main-login-help">{error}</div>',
    ],
]); ?>

<?= $form->field($model, 'username', [
    'inputOptions' => [
        'placeholder' => 'Enter Username',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
]) ?>

<?= $form->field($model, 'password', [
    'inputOptions' => [
        'placeholder' => 'Enter Password',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
])->passwordInput() ?>

<div class="scintin-pull-right">
    <a href="<?= Yii::$app->urlManager->createUrl('site/request-password-reset') ?>">Forgot password?</a>
</div>

<div class="form-group">
    <?= Html::checkbox('LoginForm[rememberMe]',true); ?>
    <?= 'Remember me' ?>
</div>

<?= Html::submitButton('Login', [
    'class' => 'btn btn-primary btn-lg btn-block',
    'name' => 'login-button',
    'type' => 'submit',
]) ?>

<?php ActiveForm::end(); ?>

frontend/views/site/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

$this->title = 'Request password reset';
/* @var $this->params['login', 'signup'] - Manually introduced variables to toggle "Active class" between
 * login and Signup pages at layout.*/
$this->params = [
    'login' => 'active',
    'signup' => '',
];
?>

<!-- New version -->
<p class="text-center mb25">Lost your password? Please enter your email address. You will receive a link to create a new password.</p>

<?php $form = ActiveForm::begin([
    'id' => 'request-password-reset-form',
    'fieldConfig' => [
        'template' => '{input}<div class="help-block help-block-error main-login-help">{error}</div>',
    ],
]); ?>

<?= $form->field($model, 'email', [
    'inputOptions' => [
        'placeholder' => 'Email address',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
]) ?>

<?= Html::submitButton('send', [
    'class' => 'btn btn-primary btn-lg btn-block',
    'name' => 'login-button',
    'type' => 'submit',
]) ?>

<?php ActiveForm::end(); ?>

frontend/views/site/resetPassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

$this->title = 'Signup';
/* @var $this->params['login', 'signup'] - Manually introduced variables to toggle "Active class" between
 * login and Signup pages at layout.*/
$this->params = [
    'login' => '',
    'signup' => 'active',
];
?>

<!-- B - New Division -->
<?php $form = ActiveForm::begin([
    'id' => 'form-signup',
    'fieldConfig' => [
    'template' => '{input}<div class="help-block help-block-error main-login-help">{error}</div>',
    ],
]); ?>

<?= $form->field($model, 'username', [
    'inputOptions' => [
        'placeholder' => 'Choose a username',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
]) ?>

<?= $form->field($model, 'password', [
    'inputOptions' => [
        'placeholder' => 'Choose a Password',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
])->passwordInput() ?>

<?= $form->field($model, 'password_repeat', [
    'inputOptions' => [
        'placeholder' => 'Repeat your Password',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
])->passwordInput() ?>

<?= Html::submitButton('Login', [
    'class' => 'btn btn-primary btn-lg btn-block',
    'name' => 'login-button',
    'type' => 'submit',
]) ?>

<?php ActiveForm::end(); ?>

frontend/views/site/signupRequest.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

$this->title = 'Signup Request';
/* @var $this->params['login', 'signup'] - Manually introduced variables to toggle "Active class" between
 * login and Signup pages at layout.*/
$this->params = [
    'login' => '',
    'signup' => 'active',
];
?>

<!-- B - New Division -->
<?php $form = ActiveForm::begin([
    'id' => 'form-signup',
    'fieldConfig' => [
    'template' => '{input}<div class="help-block help-block-error main-login-help">{error}</div>',
    ],
]); ?>

<?= $form->field($model, 'userType', [
    'inputOptions' => [
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
])->dropDownList($model->userTypeOptions); ?>

<?= $form->field($model, 'sid', [
    'inputOptions' => [
        'placeholder' => 'Please enter your SID (Admission ID / Employee ID)',
        'class' => 'form-control input-lg mb25 mb25-scintin',
    ],
]) ?>

<?= Html::submitButton('Submit', [
    'class' => 'btn btn-primary btn-lg btn-block',
    'name' => 'login-button',
    'type' => 'submit',
]) ?>

<?php ActiveForm::end(); ?>